# See [Connector Acceptance Tests](https://docs.airbyte.com/connector-development/testing-connectors/connector-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-shiftbase:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: "source_shiftbase/spec.yaml"
